### PR TITLE
DB password can now be modified

### LINKED ISSUE #86: Database ENV Variables + other DB types integration
Hi, stumbled onto this project from Reddit and I'm impressed, but while reading the README I couldn't help but notice this line:

- `Do not modify the mysql username, password and database name.`

Would it be possible to have some environment variables so those can be customized?

Also something else, it would be great to have support for other database types like Postgres.

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This would partially close #86 by allowing the database name, user and password to be modified, and it also removes unnecessary port mappings for enhanced security.

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
Nearly done. It fits all the requirements discussed before. My only grip with it is related to how "version" currently can only be "dev" and "main". I have opened #90 to discuss that point and keep it out of a PR.

**Comment by sergiolaverde0** [comment]
I have fixed the permissions for the `.gitignore` since it didn't have executable permissions yet, and also remembered to test the update from the old `deploy`. I had to do `git reset --hard HEAD` to discard all local changes but afterwards pulling was smooth, and my persistent data was all there.

Since I don't see a point in allowing for more changes, I consider this PR to be ready.

**Comment by simjanos-dev** [comment]
Thank you!

I'll merge it in a few days before v0.6, I am working on some features now.

**Comment by simjanos-dev** [comment]
Everything seems fine in the code. I've tested it with a fresh install, including #91. I cloned it from your repo. I've added `dev` as a version in a .env file I created. It works well. Git status shows no permission issues. Can i merge it in, or should I test it more?

(Asking because of my slow PC.)

**Comment by sergiolaverde0** [comment]
I also tested it as best I could so I see no reasons not to.

**Pull request merged**
