### PR TITLE
Added new test manual action

### PR DESCRIPTION
**Pull request by sergiolaverde0**
PR #81 born again.

This action allows you manually trigger a build. For it to appear in my actions list I had to move this into maineven if my goal was to target dev all along. ~~You also will need to edit the token name since mine has a typo~~ It is now fixed.

Access the action by selecting it in your action list, then on the right you will have a drop down menu to pick a branch, just above the green button to start the build process. the resulting image will be available with a :branch suffix, :dev in your case but you could also use it to test hotfixes and even a new branch for big PRs that are better tested on their own.

This has no arm64 support for faster build process. ~~You can make it faster by upgrading Node~~

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Thank you! Merged to main. Now I can just build the dev image, and try it with the `deploy` branch, by replacing

```
image: ghcr.io/simjanos-dev/linguacafe-webserver:main
image: ghcr.io/simjanos-dev/linguacafe-python-service:main
```

with

```
image: ghcr.io/simjanos-dev/linguacafe-webserver:dev
image: ghcr.io/simjanos-dev/linguacafe-python-service:dev
```

?

Also, can you please modify the `dev` branch readme to my github link? I am very tired, and afraid of messing something up. But I want to push out the update.

**Comment by simjanos-dev** [comment]
I've tried to clone the repo, and got this error:

```
laptop@laptop-mrcwx0:~/Desktop$ git clone -b deploy git@github.com:simjanos-dev/LinguaCafe.git linguacafe
Cloning into 'linguacafe'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Any idea what's wrong? I've only changed the branch and username.

**Comment by sergiolaverde0** [comment]
Yes, just like that. After the action is done check the packages in your repo and see their details, you will see the new image there with its tags visible for you to check in case you triggered on the wrong branch.

> Also, can you please modify the dev branch readme to my github link?

I knew I was missing something. I have fixed it and created a new pull request. However, I advise against pushing all this to main right now if you are feeling exhausted, that has never gone right in software development. Take a walk of half an hour if you can, or even consider merging tomorrow.

**Comment by simjanos-dev** [comment]
You are right. The dev image built and I'll merge it in tomorrow. Thank you so much for your help! This would have taken me months to learn without any direction.

I hope from now on it will be a much smoother experience both to develop and use.

If I trigger an image build by pushing to main, and I cancel the action manually. The old image will be still usable without any problem, right?

**Comment by sergiolaverde0** [comment]
Yes, it will be usable, with docker images are never overwritten so rollbacks are always possible unless you go out of your way to delete them, and I don't even know if ghcr.io allows for an easy way to do it.

**Pull request merged**
