### PR TITLE
Dockerfile refactor

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This is for the most part, a refactor of the dockerfiles to follow most* of the best practices:

- Successive `RUN` commands have been consolidated into groups according to what they do.
- Quotes were added where words could be split.
- Setup is done to ensure build fails if command before pipe fails to prevent a potentially "corrupted" image.
- `pip`now installs packages without cache.
- `apt-get` is used instead of `apt` and its cache is cleared at the end.

Those two last points allowed images to down from 1.70 GB and 1.42 GB to 1.26 GB and 1.17 GB on my fork, a little more than a 20% reduction.

This PR also removes the `.dockerignore` file added earlier since now that persistent files never touch the repo it serves no purpose. A lot of those `.gitignore` files scattered around could be deleted too but that's for another day.

Finally, it formats `docker-compose.yml` to have consistent quotation marks and indentation.

*Docker best practices also advise to pin packages versions wherever possible, but I have decided against it as per not to introduce the burden of bumping versions in a timely fashion.

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Thank you! I'll merge it in in the morning before I'll merge into main.

**Comment by simjanos-dev** [comment]
The latest docker image based on this merge did not built on [GitHub](https://github.com/simjanos-dev/LinguaCafe/actions/runs/7529579363). I'm not sure what is the issue.

**Comment by sergiolaverde0** [comment]
I will debug it when I get home, thanks for letting me know.

**Comment by simjanos-dev** [comment]
> Consider editing the Readme to leave a note about ARM support before merging to main to avoid confusion.

Didn't see the edit, and the same mac person had a problem with it...  I messed this up, I shouldn't have merged it to main yet.

There was also two other issue: there is a temp folder being shared between the python and php server. I've added an additional mount folder for it. And I've got the user database error again from a fresh install, when I opened the browser. For some reason the database doesn't get created the first time I ran `docker compose up -d` on a fresh install. This time I waited a few minutes before I opened it.

`I will debug it when I get home, thanks for letting me know.`

Thank you! Didn't meant to bother you with the lot of comments.

**Comment by sergiolaverde0** [comment]
> Didn't see the edit, and the same mac person had a problem with it... I messed this up, I shouldn't have merged it to main yet.

Probably, but what's done it's done ~~and we will probably do worse in the future~~. I have narrowed it down to `SudachiPy` failing to compile locally, and it's project page says to not support Linux-ARM which is what the image is being built from. What I don't understand is why it ever worked for them in the first place?!

> There was also two other issue: there is a temp folder being shared between the python and php server. I've added an additional mount folder for it. And I've got the user database error again from a fresh install, when I opened the browser. For some reason the database doesn't get created the first time I ran `docker compose up -d` on a fresh install. This time I waited a few minutes before I opened it.

One of them it seems like you already took care of. The other I will have to find a way to replicate it in a VM because I swear I am the only dude out there to never encounter it.

**Comment by simjanos-dev** [comment]
> I will have to find a way to replicate it in a VM because I swear I am the only dude out there to never encounter it.

I have no idea what could have cause it. `MYSQL_DATABASE: linguacafe` line in the docker compose file should add that database. And it did, on second start. I was wondering maybe it's because of the 8.0 upgrade, but I found nothing related when I googled it.

**Pull request merged**
