### PR TITLE
feat: proper ARM64 support for the python image

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This commit adds the required dependencies to successfully build the python-service image for the ARM64 instruction set, which enables it to run in Apple silicon without enabling Rosetta and to (theoretically) run in Raspberry Pi 3 or newer but for these performance is a concern.

This is also largely untested beyond checking that the image builds in CI.

Many thanks to [mateuszmrw](https://github.com/mateuszmrw) for getting SudachiPy to install in ARM!

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Thank you so much!

How should I go about testing this? Maybe start using it for beta and ask mac users to test it?

**Comment by mateuszmrw** [comment]
Hi,

I checked this branch out but it fails on installation of japanese on the arm m1 machine:

```
linguacafe-python-service-dev  |   error: subprocess-exited-with-error
linguacafe-python-service-dev  |   
linguacafe-python-service-dev  |   × Getting requirements to build wheel did not run successfully.
linguacafe-python-service-dev  |   │ exit code: 1
linguacafe-python-service-dev  |   ╰─> [22 lines of output]
linguacafe-python-service-dev  |       Traceback (most recent call last):
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
linguacafe-python-service-dev  |           main()
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
linguacafe-python-service-dev  |           json_out['return_val'] = hook(**hook_input['kwargs'])
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
linguacafe-python-service-dev  |           return hook(config_settings)
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
linguacafe-python-service-dev  |           return self._get_build_requires(
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
linguacafe-python-service-dev  |           self.run_setup()
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
linguacafe-python-service-dev  |           super(_BuildMetaLegacyBackend,
linguacafe-python-service-dev  |         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
linguacafe-python-service-dev  |           exec(compile(code, __file__, 'exec'), locals())
linguacafe-python-service-dev  |         File "setup.py", line 16, in <module>
linguacafe-python-service-dev  |           from setuptools_rust import Binding, RustExtension
linguacafe-python-service-dev  |         File "/tmp/pip-build-env-60zcm6fj/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
linguacafe-python-service-dev  |           from .build import build_rust
linguacafe-python-service-dev  |         File "/tmp/pip-build-env-60zcm6fj/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 22, in <module>
linguacafe-python-service-dev  |           from setuptools.command.build import build as CommandBuild
linguacafe-python-service-dev  |       ModuleNotFoundError: No module named 'setuptools.command.build'
linguacafe-python-service-dev  |       [end of output]
```

I think it required pip --upgrade on the setuptools and wheel otherwise it the japanese installation will fail.

**Comment by mateuszmrw** [comment]
Hi,

I moved the changes from the PythonDockerfile to PythonDockerfileDev and tried to run it on my m1 mac.
It fails on the Japanese installation:

```
linguacafe-python-service-dev  |   error: subprocess-exited-with-error
linguacafe-python-service-dev  |   
linguacafe-python-service-dev  |   × Building wheel for sudachipy (pyproject.toml) did not run successfully.
linguacafe-python-service-dev  |   │ exit code: 1
linguacafe-python-service-dev  |   ╰─> [37 lines of output]
linguacafe-python-service-dev  |       running bdist_wheel
linguacafe-python-service-dev  |       running build
linguacafe-python-service-dev  |       running build_py
linguacafe-python-service-dev  |       creating build
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310/sudachipy
linguacafe-python-service-dev  |       copying py_src/sudachipy/config.py -> build/lib.linux-aarch64-cpython-310/sudachipy
linguacafe-python-service-dev  |       copying py_src/sudachipy/command_line.py -> build/lib.linux-aarch64-cpython-310/sudachipy
linguacafe-python-service-dev  |       copying py_src/sudachipy/__init__.py -> build/lib.linux-aarch64-cpython-310/sudachipy
linguacafe-python-service-dev  |       copying py_src/sudachipy/errors.py -> build/lib.linux-aarch64-cpython-310/sudachipy
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310/sudachipy/dictionary
linguacafe-python-service-dev  |       copying py_src/sudachipy/dictionary/__init__.py -> build/lib.linux-aarch64-cpython-310/sudachipy/dictionary
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310/sudachipy/tokenizer
linguacafe-python-service-dev  |       copying py_src/sudachipy/tokenizer/__init__.py -> build/lib.linux-aarch64-cpython-310/sudachipy/tokenizer
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310/sudachipy/morphemelist
linguacafe-python-service-dev  |       copying py_src/sudachipy/morphemelist/__init__.py -> build/lib.linux-aarch64-cpython-310/sudachipy/morphemelist
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310/sudachipy/morpheme
linguacafe-python-service-dev  |       copying py_src/sudachipy/morpheme/__init__.py -> build/lib.linux-aarch64-cpython-310/sudachipy/morpheme
linguacafe-python-service-dev  |       copying py_src/sudachipy/sudachipy.pyi -> build/lib.linux-aarch64-cpython-310/sudachipy
linguacafe-python-service-dev  |       creating build/lib.linux-aarch64-cpython-310/sudachipy/resources
linguacafe-python-service-dev  |       copying py_src/sudachipy/resources/sudachi.json -> build/lib.linux-aarch64-cpython-310/sudachipy/resources
linguacafe-python-service-dev  |       copying py_src/sudachipy/resources/unk.def -> build/lib.linux-aarch64-cpython-310/sudachipy/resources
linguacafe-python-service-dev  |       copying py_src/sudachipy/resources/rewrite.def -> build/lib.linux-aarch64-cpython-310/sudachipy/resources
linguacafe-python-service-dev  |       copying py_src/sudachipy/resources/char.def -> build/lib.linux-aarch64-cpython-310/sudachipy/resources
linguacafe-python-service-dev  |       running build_ext
linguacafe-python-service-dev  |       running build_rust
linguacafe-python-service-dev  |       error: can't find Rust compiler
linguacafe-python-service-dev  |       
linguacafe-python-service-dev  |       If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
linguacafe-python-service-dev  |       
linguacafe-python-service-dev  |       To update pip, run:
linguacafe-python-service-dev  |       
linguacafe-python-service-dev  |           pip install --upgrade pip
linguacafe-python-service-dev  |       
linguacafe-python-service-dev  |       and then retry package installation.
linguacafe-python-service-dev  |       
linguacafe-python-service-dev  |       If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
linguacafe-python-service-dev  |       [end of output]
linguacafe-python-service-dev  |   
linguacafe-python-service-dev  |   note: This error originates from a subprocess, and is likely not a problem with pip.
linguacafe-python-service-dev  |   ERROR: Failed building wheel for sudachipy
linguacafe-python-service-dev  | ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sudachipy)
```

Cargo path issue probably?

**Comment by simjanos-dev** [comment]
I think you can try using the image @sergiolaverde0 made [here](https://github.com/sergiolaverde0/LinguaCafe/pkgs/container/linguacafe-webserver). (Btw, it says v0.11.4. I don't know if that could cause any issues) If github builds it, then it's okay, except for dev environments where everyone have to build their own image.

**Comment by sergiolaverde0** [comment]
> How should I go about testing this?

Well mateus just began testing it.

> It fails on the Japanese installation

I was about to propose to use the image I built just as simjanos did since it [seemed to have worked](https://github.com/sergiolaverde0/LinguaCafe/actions/runs/9718505198/job/26826529238#step:9:3582) there.

> Cargo path issue probably?

Very likely, since the dev version does not set up an user. Give me a couple of minutes and I will push to this branch.

**Comment by mateuszmrw** [comment]
Ok, it seems to be working without any changes! I guess I did something wrong when setting up the PythonDockerfileDev for my testing.

I built the image: `ghcr.io/sergiolaverde0/linguacafe-python-service:v0.11.4` using a installation with docker-compose on m1 mac and it is working!

Sorry for creating confusion. Could you update the PythonDockerfileDev as well and remove docker-compose-macos.yml too?

**Comment by simjanos-dev** [comment]
> Could you update the PythonDockerfileDev as well and remove docker-compose-macos.yml too?

And please do the beta image builder github file too. I will create a beta image for this in a few weeks, when the import changes are finished and tested.

**Comment by sergiolaverde0** [comment]
> it seems to be working without any changes!

Nice.

> Could you update the PythonDockerfileDev as well and remove docker-compose-macos.yml too?

Done.

> please do the beta image builder github file too

Done from the beginning, actually. `dev` builder remains being exclusive to AMD64 as we originally planned for much faster build times.

**Comment by relrod** [comment]
@simjanos-dev Any chance of this merging sometime soon? I need arm images for my homelab deployment of this :) 

If there's anything this needs to get it over the finish line, I'm happy to help that effort.

**Comment by simjanos-dev** [comment]
I can merge it if you want it in the dev environment. 

However Im in the middle of adding a translation service as a dictionary like deepl, and it will need some refactoring before I can implement it properly. 

After its done, I want to release a beta image.

**Comment by relrod** [comment]
In the dev branch would unblock me for now and at least tell me if my attempt at a kube config worked, so I'd be happy with that! :+1:

**Comment by simjanos-dev** [comment]
@relrod Okay. I'm going to need a few days at least to finish the stuff before the beta image. 

@sergiolaverde0 @mateuszmrw Thank you so much for this PR!

**Comment by simjanos-dev** [comment]
I should remove the `platform: ${PLATFORM:-}` part of the `docker-compose.yml` file, right?

**Comment by simjanos-dev** [comment]
Unfortunately the [beta build has failed](https://github.com/simjanos-dev/LinguaCafe/actions/runs/11090949786/job/30813957594). It is the same error that mateuszmrw had.

**Comment by sergiolaverde0** [comment]
Failed on my end too. However, the error is on a different step than it was for mateuszmrw, and seems to be unrelated to the rust toolchain. I will try to see why spacy itself is giving issues when it worked fine before.

**Comment by simjanos-dev** [comment]
Sorry, I dont know why I confused the two things, the error message is totally different. 

Ill try to check as well in the next few days. I made a dev image that worked, maybe I messed up when adding something to the prod python dockerfile.

**Comment by simjanos-dev** [comment]
The python dockerfile and docker-compose file look the same. I built a dev image now and it worked. I think I also built my dev environment last week.

**Comment by simjanos-dev** [comment]
@sergiolaverde0 

Can you please help me how can I set up a docker compose file that builds the same image locally as github main and beta actions? Or how to modify my current dev environment file. 

I'm unsure how to test and fix why the github beta image building is failing.

**Comment by simjanos-dev** [comment]
I've figured it out. For some reason it did not let me build multiplatform images, but solved it after some googling.

I got this error message:
```
=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   [COMMAND] gcc -c /tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/frame/util/bli_util_oapi.c -o /tmp/tmp_lf2z51w/bli_util_oapi.o -O2 -fPIC -std=c99 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   [COMMAND] gcc -c /tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/frame/util/bli_util_oapi_ex.c -o /tmp/tmp_lf2z51w/bli_util_oapi_ex.o -O2 -fPIC -std=c99 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   [COMMAND] gcc -c /tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/frame/util/bli_util_tapi_ba.c -o /tmp/tmp_lf2z51w/bli_util_tapi_ba.o -O2 -fPIC -std=c99 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   [COMMAND] gcc -c /tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/frame/util/bli_util_tapi.c -o /tmp/tmp_lf2z51w/bli_util_tapi.o -O2 -fPIC -std=c99 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   [COMMAND] gcc -c /tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/frame/util/bli_util_tapi_ex.c -o /tmp/tmp_lf2z51w/bli_util_tapi_ex.o -O2 -fPIC -std=c99 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   [COMMAND] gcc -c /tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/frame/util/bli_util_unb_var1.c -o /tmp/tmp_lf2z51w/bli_util_unb_var1.o -O2 -fPIC -std=c99 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.9.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-arm64 -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64
1080.1                   creating build/temp.linux-aarch64-3.10
1080.1                   creating build/temp.linux-aarch64-3.10/blis
1080.1                   aarch64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/include -I/tmp/pip-install-ugfl0dn6/blis_45aebc04f29147ad9c7174127ddbf715/blis/_src/include/linux-arm64 -I/tmp/pip-build-env-j3gf9riv/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/usr/include/python3.10 -c blis/cy.c -o build/temp.linux-aarch64-3.10/blis/cy.o -std=c99
1080.1                   blis/cy.c:32:10: fatal error: Python.h: No such file or directory
1080.1                      32 | #include "Python.h"
1080.1                         |          ^~~~~~~~~~
1080.1                   compilation terminated.
1080.1                   error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
1080.1                   [end of output]
1080.1       
1080.1               note: This error originates from a subprocess, and is likely not a problem with pip.
1080.1               ERROR: Failed building wheel for blis
1080.1             Failed to build blis
1080.1             ERROR: Could not build wheels for blis, which is required to install pyproject.toml-based projects
1080.1             [end of output]
1080.1       
1080.1         note: This error originates from a subprocess, and is likely not a problem with pip.
1080.1       error: subprocess-exited-with-error
1080.1       
1080.1       × pip subprocess to install build dependencies did not run successfully.
1080.1       │ exit code: 1
1080.1       ╰─> See above for output.
1080.1       
1080.1       note: This error originates from a subprocess, and is likely not a problem with pip.
1080.1       [end of output]
1080.1   
1080.1   note: This error originates from a subprocess, and is likely not a problem with pip.
1080.1 error: subprocess-exited-with-error
1080.1 
1080.1 × pip subprocess to install build dependencies did not run successfully.
1080.1 │ exit code: 1
1080.1 ╰─> See above for output.
1080.1 
1080.1 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/dev/.buildkit_qemu_emulator /bin/bash -o pipefail -c pip install -U --no-cache-dir         pip         setuptools         wheel         lxml         lxml_html_clean         youtube_transcript_api         ebooklib         pykakasi         bottle         spacy         pinyin         pysub-parser         newspaper3k" did not complete successfully: exit code: 1
```

And I'm stuck again.

I kind of feel overwhelmed nowadays with so many issues with python/arm/docker. I don't think I can maintain this many things I'm not very familiar with in the long term if they break frequently, especially if Stanza gets added.

**Comment by sergiolaverde0** [comment]
I feel you, this part is closer to DevOps than actual programming.

From what I see is that when we try to install `spacy` it also tries to install its dependencies first to ensure they aren't broken, one of them being `bliss`, a Python wrapper around a C library that does not provide prebuilt binaries for arm64 so `pip` tries to compile it from source instead to satisfy the requirement (this happens with a lot of packages and is part of why arm64 images take ages to build).

The compilation is failing which in turn causes the whole job to fail rather than produce a "wrong" output. It seems to be because of missing header, and *might* get solved by installing `python3-dev` via `apt`; I'm currently testing this in my fork, let's see if the solution is that easy.

I don't know why it worked for me before.

**Comment by sergiolaverde0** [comment]
It worked! See #368

**Comment by simjanos-dev** [comment]
Thank you so much! I would have had no idea what to do about it, other than asking on a forum or something. 

> The compilation is failing which in turn causes the whole job to fail rather than produce a "wrong" output. It seems to be because of missing header, and might get solved by installing python3-dev via apt; I'm currently testing this in my fork, let's see if the solution is that easy.

I don't understand it completely. If it can't compile something, shouldn't it fail like it does, because otherwise there would be missing code? How does python3-dev fixes it?

Does adding new python packages always have a risk of not having ARM support?

**Comment by simjanos-dev** [comment]
> and is part of why arm64 images take ages to build

Jesus, that is an understatement, it is still going. Don't know if it is working yet, but did not throw an error at the same point. 

```
[+] Building 4152.6s (32/34)
```

Can it cause problems due to the webserver image being done earlier?

**Comment by sergiolaverde0** [comment]
> How does python3-dev fixes it?

It provides the missing header file and so compilation can succeed.

> Does adding new python packages always have a risk of not having ARM support? 

I am not really sure to be honest. Pure Python packages won't have issues with the instruction set, and without being an expert I think most wrappers for C and Rust should compile fine. Unless you use some library with crazy hand made optimizations in assembly I think it will be fine.

> Should I remove the  `platform: ${PLATFORM:-}` part from the docker-compose file? 

For the stable release you should, for the beta you should mention it when you announce it via social media instead, so users of the stable release don't get confused.

> Can it cause problems due to the webserver image being done earlier?

I don't think so, images are independent.

> Can ARM mac devs still use amd64 version if I restore the docker-compose-dev-macos.yml file that was deleted in this PR?

It will need some changes to account for the websockets but otherwise yes. They can also do the trick of mounting the source code for the web server as a volume instead of copying it into the image, so that they don't need a rebuild but just restart the server instead.

> I needed to use this for multi platform builds to work. I have no idea why/how it workes

Building an image for a different instruction set requires a virtual machine and a bit of witchcraft, that command apparently is an easier way to do it by hiding away some details. That's why your error message said something about Qemu.

**Comment by simjanos-dev** [comment]
I removed the native ARM support temporarily, because the github build action was going on for over 2 hours and still didn't finish yet. I plan to release updates frequently, so I'll implement it again later on.

**Pull request merged**
