### PR TITLE
Improved German support

### PR DESCRIPTION
**Pull request by mbrine555**
This PR is a quick attempt at improving the support for German. There were two main issues that I wanted to try to address:

1. Noun Gender

Like many other languages, [German has the concept of grammatical gender for nouns](https://en.wikipedia.org/wiki/Grammatical_gender_in_German). When learning, it is useful to have the definite article along with the actual noun, since it can be difficult to determine the gender without it. This adds the definite article to the lemma (similar to what is already happening with Norwegian).

2. Separable Verbs

German also has the quirk of [separable verbs](https://en.wikipedia.org/wiki/Separable_verb). This means that sometimes the prefix/particle and the base verb do not appear together. The change here makes it so that sentences like 

```
Ich greife den Feind an.
Ich habe den Feind angegriffen.
```

both have `angreifen` as the verb lemma. This does create a bit of weirdness in the UI, because it does not identify `greife` and `an` as being part of the same word. Rather, it just shows `angreifen` as the base word when highlighting `greife`. It might also create some weirdness if people upgrade their instances in place.

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Thank you so much! This looks great. 

> This does create a bit of weirdness in the UI, because it does not identify greife and an as being part of the same word. Rather, it just shows angreifen as the base word when highlighting greife. It might also create some weirdness if people upgrade their instances in place.


I'm sorry, but I don't really understand it completely. I'll test it out so maybe I'll understand it a bit better.

Is the old or the new version(that you commited) cause problems in the UI? If the new version cause some issues, can it be improved?

**Comment by simjanos-dev** [comment]
Tested it, it works great. Thank you, it's really valuable for German learners! I'll merge it in. 

I'll also convert lemmas to lowercase by default. I never noticed it, but sometimes the lemma has an uppercase letter in it.

**Comment by mbrine555** [comment]
> I'm sorry, but I don't really understand it completely. I'll test it out so maybe I'll understand it a bit better.
> 
> Is the old or the new version(that you commited) cause problems in the UI? If the new version cause some issues, can it be improved?

Sure, I can explain a bit more. 

Because we're just changing the lemma for the main verb and not the prefix, it leads to the case where the main verb gets correctly identified:
verb

but the prefix still looks like it's its own word:
prefix

So in the case that someone has both `angreifen` and `an` as un-encountered words, they could click on `greife`, define it, and `an` will still show up as unknown even though we know it's technically part of the verb and not its own thing. I think it's pretty minor, but I figured I would point it out just in case.

I suppose we could also change the lemma for the prefix in this case to `angreifen`? Not sure of all of the data implications for that, or if it even helps solve the problem.

**Comment by simjanos-dev** [comment]
It helped me understand it a little bit more, thank you! 

I think this looks usable if someone knows the language a bit.

I've merged it into dev branch, and will add it to the next version in a few days. Unfortunately there is no option to override generated lemmas yet, I'll add it in the future, so people can update lemmas if they re-import texts again.

**Comment by TheNomad11** [comment]
> I'll also convert lemmas to lowercase by default. I never noticed it, but sometimes the lemma has an uppercase letter in it.

Is this the reason German nouns are lowercase by default although it is supossed to be uppercase? German nouns always start with a capital letter. der Fußball instead of fußball! Any way you can revert that @simjanos-dev ?

screen-2025-05-22-22-16-17

**Pull request merged**
