### PR TITLE
fix: add missing package for Thai language

### PR DESCRIPTION
**Pull request by sergiolaverde0**

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
One moment, this is failing on testing, let me look closer.

**Comment by simjanos-dev** [comment]
Thank you so much!

**Comment by sergiolaverde0** [comment]
When capitalizing the language names in the parts that involve language install their lowercase names were preserved in the `getTokenizerDoc` function so it is failing for me. Do I change them all back to lowercase or do I capitalize them in the function too? If it is the later, should I capitalize the languages that are shipped by default too?

**Comment by simjanos-dev** [comment]
> When capitalizing the language names in the parts that involve language install their lowercase names were preserved in the getTokenizerDoc function so it is failing for me.

That is weird. Are you sure that's the case? Because for me Thai and Turkish are working. 

getTokenizerDoc is getting lower case language names currently. Why are the two parts of the file are related?

**Comment by simjanos-dev** [comment]
There's a part in the current PR:
```
elif lang == "thai":
```

This has no If counterpart, and I think only this should be uppercase `Thai` instead of `thai`. I think the `getTokenizerDoc` could be left unchanged.

**Comment by sergiolaverde0** [comment]
You are right, false alarm. This is ready for merge.

**Comment by simjanos-dev** [comment]
Are you sure? I'm not good at python, so I don't understand it completely, but that elif has no if:

```
subprocess.check_output(
            [
                "pip",
                "install",
                "--target=/var/www/html/storage/app/model",
                model_url[lang],
            ]
        )
        elif lang == "thai":
            subprocess.check_output([
                "pip",
                "install",
                "--target=/var/www/html/storage/app/model",
                "tzdata"])
```

**Comment by sergiolaverde0** [comment]
Fixed. My stash was interfering.

**Comment by simjanos-dev** [comment]
Thank you!

**Pull request merged**
