### PR TITLE
Rus swe ukr lang

### PR DESCRIPTION
**Pull request by systemcrash**
( Implies PR #51 )

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Wow. This is great, thank you so much. Working on some stuff, but will merge it soon.

**Comment by simjanos-dev** [comment]
It became too much for my laptop to handle. Is there any way to use one config file to enable/disable languages in php, javascript, python and dockerfile at the same time?

**Comment by systemcrash** [comment]
> It became too much for my laptop to handle. Is there any way to use one config file to enable/disable languages in php, javascript, python and dockerfile at the same time?

There's a way, but nothing I have thought of yet. It is not easy to please various computer languages at once.

A `.ini` file comes to mind. 

Which part seems to be problematic?

**Comment by simjanos-dev** [comment]
I'm not even sure if it's actually an issue and worth doing, or is it just me. I have a laptop with 8GB ram, I gave docker 1.89GB. Whenever i build my docker image(after docker prune for testing) and start it up the first time it takes a lot of time and my laptop freezes for a minute. I think it's because of the many spacy models, but I'm not sure.

**Comment by sergiolaverde0** [comment]
Spacy is most likely the culprit, so enabling/disabling in Python only would get you 90% there.
I have been eyeing the speed at which the images have been growing up as language support increases, but I wasn't really sure of a way to handle it other than splitting the images by language groups, which is more neatly done after merging PR #48, and even then it remains non-trivial.

**Pull request merged**
