### PR TITLE
Container processes no longer run as root

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This commit creates a dedicated user to run the process inside the container, which also gets ownership of the folders that are bound to the host container to prevent any possible permission issue.

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
I have decided to go against your petition delaying the switch of the python container to run rootless for the next release, because applying the change to both containers at the same time means users only have to modify the permissions once.

While doing this the "fake" error when installing a new language went away, it was very likely related to the models folder still having root ownership when everything else didn't, so you don't have to worry about that.

**Comment by simjanos-dev** [comment]
> I have decided to go against your petition delaying the switch of the python container to run rootless for the next release, because applying the change to both containers at the same time means users only have to modify the permissions once.

Okay, I trust you with it! I did not know that it would require sudo chmod twice.

> While doing this the "fake" error when installing a new language went away, it was very likely related to the models folder still having root ownership when everything else didn't, so you don't have to worry about that.

That's nice, then there are not tasks left!

Does these changes work for the dev environment as well if I replicate them in the 3 dev files? Would you like to do it, or would you like me to do it? 

I will merge this in probably today, and I'll test it on both dev environment and create a dev image.

Thank you so much for your work! (Someone on discord will be very happy for it, because git does not work for them)

**Comment by sergiolaverde0** [comment]
Whenever I make changes to the Dockerfiles I always forget about the dev versions.

entrypoint-dev can probably be left as is since you mount the nearly empty (in the future they will only have .gitkeep files) storage folders, but replicating the change to them might allow you to get rid of those. And if in the future you add a new folder you might be tempted to simply create it without updating the script and the oversight won't be caught in your development setup so it is better to replicate.

For the PHP-dev side you need to remove the `chown -R laravel /var/www/html` because the path does not exist in the container, you mount it to make dev task easier.

For the Python-dev side you can replicate as is without side effects.

The compose-dev file is bound to port 81, it might work but if you encounter issues try moving it to a port where you don't need privileges. I see no other issues.

**Comment by simjanos-dev** [comment]
> For the PHP-dev side you need to remove the chown -R laravel /var/www/html because the path does not exist in the container, you mount it to make dev task easier.

I was already missing `SHELL ["/bin/bash", "-o", "pipefail", "-c"]` from the PhpDockerfileDev. 

What does this line do, why is this necessary?
```
CMD [ "export PYTHONPATH=\"${HOME}/.local/bin:${PYTHONPATH}\"" ]
```

I [updated my dev files](https://github.com/simjanos-dev/LinguaCafe/commit/e95ff63892ea5be47fcffd9f5221a69fc6efad57). Can you please check if everything is good with them?

After you responed I'll try to rebuild my dev environment, If it works I will create a dev image and test on my personal linguacafe instance, then if I find no problems, v0.12 is ready. It will only need user manual and readme updates.

This will still require a sudo chmod 777 once, right? (Sorry, I am a bit confused about this.)

**Comment by sergiolaverde0** [comment]
> What does this line do, why is this necessary?
> 
> ```
> CMD [ "export PYTHONPATH=\"${HOME}/.local/bin:${PYTHONPATH}\"" ]
> ```

To be honest, I'm not completely sure it is needed but I added it to be 200% positive the packages installed by the non root user into its own home directory are taken as part of the path, since `pip install` no longer runs as root. It might not be needed, and I will certainly go back to that file to add a proper entrypoint eventually, but not for this release.

> I [updated my dev files](https://github.com/simjanos-dev/LinguaCafe/commit/e95ff63892ea5be47fcffd9f5221a69fc6efad57). Can you please check if everything is good with them?

Looks good to me.

> This will still require a sudo chmod 777 once, right? (Sorry, I am a bit confused about this.)

Yes. current files are many owned by root user (you can check it) so the command is needed to give the new users inthe containers permission to read them. In theory you can do `sudo chown myuser:mygroup -R ./storage` but is more complicated since people would have to check their user and group beforehand (shell expansion does not work with, I tried it).

Also note there is no need to touch the database folder and I don't think we should.

**Pull request merged**
