### PR TITLE
Updated README.md with new quickstart and migration instructions

### PR DESCRIPTION
**Pull request by sergiolaverde0**
Added instructions for a quickstart using the new branch from PR #79.

Instructions are by nature a very opinionated thing and you are probably more used to dealing with non-tech savvy people than I am, so go ahead and modify it to your heart's content. Let me know if anything gives you any problem.

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
In my head if it is a single command they should be fine, but you know your userbase best. I have made a small test and I was able to delete books with missing covers back on the v0.4 image. I am in favor of going ahead with it, but asking for people's opinion can be enlightening when it is something that concerns them as is the case here.

**Comment by simjanos-dev** [comment]
Oh, ff you deleted it, and it disappeared, then it's fine 100%. I thought it would throw an error.

**Comment by sergiolaverde0** [comment]
I have chained the commands together in the `README.md` and renamed the new folder in the migration part to be 100% positive it is different from the folder name that was present for the older version, thus avoiding confusion.

**Comment by simjanos-dev** [comment]
I hope they will able to update. I've added an additional info line in dev branch after I merged it.

**Pull request merged**
