### PR TITLE
Fixed race condition by the power of POSIX sh

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This *might* close issue #69 by simply retrying `php artisan migrate` every 15 seconds if it fails until it doesn't or until it has failed so many times it is clear it won't fix itself if left alone. It also *might* make the health check redundant so I removed it. `README.md` was updated accordingly not to falsely alarm users by an issue hat was *presumably* fixed.

I have never encountered this issue so testing this was impossible. Rather than waste your time and mess your repo by merging this, I encourage you or someone facing this issue to try my PHP image first, over at `ghcr.io/sergiolaverde0/linguacafe-webserver:v0.4.4`; leave the other images as they are.

Race conditions are a particularly annoying bug to deal with so test this as extensively as possible before claiming it has been actually fixed, and let me know if it wasn't.

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
I understand that, that's why I suggested using my image, to save you half an hour of build time on that action.

**Comment by simjanos-dev** [comment]
I'll test this and [Quick start setup](https://github.com/sergiolaverde0/LinguaCafe/commit/b1af922f2330ba6f15b44c4de2387c0cffcb8265) tomorrow, and I'll probably release the next patch in a few days. 

I wanted to do everything in one patch, but I rather cut the patch in two, because I've fixed a lot of things, and the rest is new features. 

Thank you for helping me with docker, I'm really grateful!

**Comment by sergiolaverde0** [comment]
Be warned, the reason I haven't opened a PR for the quick start setup is because it isn't completely done yet.

So far it seems to work for everything I know to test for people starting from a fresh install (and without `sudo`), but I still need to triple check the migration steps for already existing installs (those need `sudo` so instructions must be foolproof) and to put them down in the `README.md`.

You can merge it and tell people to start using it already, just be warned with what you tell the already existing users.

**Comment by simjanos-dev** [comment]
Okay, I'll wait for the PR. 

I'll also have to:
- Move the flags to the public directory.
- Write a Laravel migration to rename all ebook covers to default. 

I think I'll have it tomorrow. I'll start using it myself for a few days before I merge it in.

**Comment by simjanos-dev** [comment]
I've got this error message:

`validating /home/laptop/Desktop/LinguaCafeNewDockerTest/docker-compose.yml: services.webserver.depends_on must be a list`

I've replaced:
```
depends_on:
            mysql
```

with:

```
depends_on:
            - mysql
```

Now it's downloading.

**Comment by simjanos-dev** [comment]
It did not work. I've got the  usual error, then restarted:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'linguacafe.users' doesn't exist (SQL: select * from `users` where `id` = 1 limit 1).`

This time restarting did not help either. This is the whole log of my webserver container:

```
2024-01-20 15:42:46 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:43:01 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:43:16 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:43:32 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:43:47 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:44:02 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:44:17 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:44:36 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:44:51 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:45:06 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:45:23 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:45:38 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:46:54 Seeding: Database\Seeders\SettingsSeeder
2024-01-20 15:46:56 
2024-01-20 15:46:56    Illuminate\Database\QueryException 
2024-01-20 15:46:56 
2024-01-20 15:46:56   SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `settings` where `name` = deeplApiKey limit 1)
2024-01-20 15:46:56 
2024-01-20 15:46:56   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
2024-01-20 15:46:56     708▕         // If an exception occurs when attempting to run a query, we'll format the error
2024-01-20 15:46:56     709▕         // message to include the bindings with SQL, which will make this exception a
2024-01-20 15:46:56     710▕         // lot more helpful to the developer instead of just the database's errors.
2024-01-20 15:46:56     711▕         catch (Exception $e) {
2024-01-20 15:46:56   ➜ 712▕             throw new QueryException(
2024-01-20 15:46:56     713▕                 $query, $this->prepareBindings($bindings), $e
2024-01-20 15:46:56     714▕             );
2024-01-20 15:46:56     715▕         }
2024-01-20 15:46:56     716▕     }
2024-01-20 15:46:56 
2024-01-20 15:46:56       +23 vendor frames 
2024-01-20 15:46:56   24  database/seeders/SettingsSeeder.php:17
2024-01-20 15:46:56       Illuminate\Database\Eloquent\Builder::first()
2024-01-20 15:46:56 
2024-01-20 15:46:56       +7 vendor frames 
2024-01-20 15:46:56   32  database/seeders/DatabaseSeeder.php:16
2024-01-20 15:46:56       Illuminate\Database\Seeder::call("Database\Seeders\SettingsSeeder")
2024-01-20 15:52:13 172.18.0.1 - - [20/Jan/2024:14:52:11 +0000] "GET / HTTP/1.1" 500 637270 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2024-01-20 15:52:13 172.18.0.1 - - [20/Jan/2024:14:52:13 +0000] "GET /favicon.ico HTTP/1.1" 200 296 "http://lingua.cafe:9191/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2024-01-20 15:46:59 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
2024-01-20 15:46:59 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
2024-01-20 15:47:01 [Sat Jan 20 14:47:01.320585 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.14 configured -- resuming normal operations
2024-01-20 15:47:01 [Sat Jan 20 14:47:01.397375 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
2024-01-20 15:53:11 [Sat Jan 20 14:53:11.514558 2024] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
2024-01-20 15:53:17 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:53:32 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:53:47 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:54:02 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:54:17 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:54:32 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
2024-01-20 15:54:47 /var/www/html/entrypoint.sh: 5: php artisan migrate: not found
```

**Comment by sergiolaverde0** [comment]
Crap, I messed up with those quotes.Sorry about both those issues, I forgot to properly test it on the excuse that I had never encountered the target bug. That was lazy on my part.

I have fixed and tested that it actually starts on a new version, tagged v0.4.5 on my fork.

**Comment by simjanos-dev** [comment]
Thank you! I think it will take 2-3 hours to test all the now dockers stuff for me: :( I really want to get this update out today if possible.

**Comment by simjanos-dev** [comment]
It worked! It took my MySQL server over 4 minutes to boot. So I would increase the retry count to 6 minutes. Not sure what's wrong with my laptop. I allocated 4 out of 8 cores and 3GB out of 8GB ram for it. I will do a final test later, after I merged in the other PRs.

```
2024-01-20 16:42:46 2024-01-20 15:42:46+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.36-1.el8 started.
2024-01-20 16:42:50 2024-01-20 15:42:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-01-20 16:42:50 2024-01-20 15:42:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.36-1.el8 started.
2024-01-20 16:42:51 2024-01-20 15:42:51+00:00 [Note] [Entrypoint]: Initializing database files
2024-01-20 16:42:51 2024-01-20T15:42:51.610506Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2024-01-20 16:42:51 2024-01-20T15:42:51.611765Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.36) initializing of server in progress as process 80
2024-01-20 16:42:51 2024-01-20T15:42:51.653226Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2024-01-20 16:43:14 2024-01-20T15:43:14.793667Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2024-01-20 16:43:23 2024-01-20T15:43:23.222677Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2024-01-20 16:45:31 2024-01-20 15:45:31+00:00 [Note] [Entrypoint]: Database files initialized
2024-01-20 16:45:31 2024-01-20 15:45:31+00:00 [Note] [Entrypoint]: Starting temporary server
2024-01-20 16:45:32 mysqld will log errors to /var/lib/mysql/de70576eb2f9.err
2024-01-20 16:45:34 mysqld is running as pid 126
2024-01-20 16:45:34 2024-01-20 15:45:34+00:00 [Note] [Entrypoint]: Temporary server started.
2024-01-20 16:45:34 '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2024-01-20 16:45:39 Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
2024-01-20 16:45:39 Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
2024-01-20 16:45:39 Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
2024-01-20 16:46:01 Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
2024-01-20 16:46:01 Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
2024-01-20 16:46:01 Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
2024-01-20 16:46:04 2024-01-20 15:46:04+00:00 [Note] [Entrypoint]: Creating database linguacafe
2024-01-20 16:46:04 2024-01-20 15:46:04+00:00 [Note] [Entrypoint]: Creating user linguacafe
2024-01-20 16:46:05 2024-01-20 15:46:05+00:00 [Note] [Entrypoint]: Giving user linguacafe access to schema linguacafe
2024-01-20 16:46:05 
2024-01-20 16:46:05 2024-01-20 15:46:05+00:00 [Note] [Entrypoint]: Stopping temporary server
2024-01-20 16:46:09 2024-01-20 15:46:09+00:00 [Note] [Entrypoint]: Temporary server stopped
2024-01-20 16:46:09 
2024-01-20 16:46:09 2024-01-20 15:46:09+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
2024-01-20 16:46:09 
2024-01-20 16:46:11 2024-01-20T15:46:11.469086Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2024-01-20 16:46:11 2024-01-20T15:46:11.487840Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.36) starting as process 1
2024-01-20 16:46:11 2024-01-20T15:46:11.505633Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2024-01-20 16:46:14 2024-01-20T15:46:14.616202Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2024-01-20 16:46:16 2024-01-20T15:46:16.234891Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2024-01-20 16:46:16 2024-01-20T15:46:16.238015Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2024-01-20 16:46:16 2024-01-20T15:46:16.266625Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2024-01-20 16:46:16 2024-01-20T15:46:16.356608Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2024-01-20 16:46:16 2024-01-20T15:46:16.356685Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
```

**Comment by sergiolaverde0** [comment]
Increasing the number of attempts is trivial but has the downside that if you set it too high it won't go down even when something has gone terribly wrong and further attempts won't achieve anything but waste the user's time.

10 minutes is still short enough for this not to be a concern, but keep an eye out for users reporting issues related to this.

**Comment by simjanos-dev** [comment]
Thank you! This should work.

**Pull request merged**
