### PR TITLE
Feat/add windows installer

### LINKED ISSUE #49: Windows installation process.
Can someone please write an installation and update process guide in the readme file for windows, using the latest method in the dev branch? I only have access to one windows machine, and I couldn't get docker working on it.

It would also be great, if all the commands could be run by clicking on a single install.bat and update.bat file, because there are many people in the language learning community who do not use CMD at all, and it would make it a lot easier for them. I don't know if this is possible or not.

### PR DESCRIPTION
**Pull request by TLaborde**
Add a simple batch file for windows installation. Should resolve  #49 

* check if git is installed
* check if docker is installed
* allow to install in a different folder
* update if an existing version is detected
* open LinguaCafe once the containers are running

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Wow, this looks great. Thank you so much! With this people should be able to install it even without terminal skills (except if something goes wrong).

I have a few things though. 
- Could you please remove the open webpage part? I think it would be better to just display a message something like "Your LinguaCafe server has started, you can soon open it in your browser on this url: http://localhost:9191. Sometimes this can take a few minutes on slower PC-s.", and keep the terminal open. I feel like it's better not to auto open a browser.
- I think we should make it as simple as possible, and just always use the folder that the .bat file was placed. A lot of users who have  a problem with using the command line would also have a problem providing a path. Instead we could display the folder path including the linguacafe folder that will be created, and allow the user to confirm or cancel the installation?
- Can you please rebase it to the `dev` branch? `main` branch only gets full versions merged.
- `chmod 777 -R` part was necessary because if the git cloned storage/temp folder did not have writing permissions, we couldn't import e-book files. Can you please try if importing e-books works with this method? Or even add a windows version of the same command to be sure?


I will try to install it once again on a windows machine this evening, and will merge it in. This will be a huge help for some people.

**Comment by simjanos-dev** [comment]
I've tested it on a Windows machine, It works perfectly. This is great :) One issue I had is that windows defender marked the .bat file as a virus. I think it was because of the open browser part.

**Comment by TLaborde** [comment]
- [x] Could you please remove the open webpage part? I think it would be better to just display a message something like "Your LinguaCafe server has started, you can soon open it in your browser on this url: http://localhost:9191/. Sometimes this can take a few minutes on slower PC-s.", and keep the terminal open. I feel like it's better not to auto open a browser.
- [x] I think we should make it as simple as possible, and just always use the folder that the .bat file was placed. A lot of users who have a problem with using the command line would also have a problem providing a path. Instead we could display the folder path including the linguacafe folder that will be created, and allow the user to confirm or cancel the installation?
- [x] Can you please rebase it to the dev branch? main branch only gets full versions merged.
- [x] chmod 777 -R part was necessary because if the git cloned storage/temp folder did not have writing permissions, we couldn't import e-book files. Can you please try if importing e-books works with this method? Or even add a windows version of the same command to be sure?

`chmod 777 -R` is not necessary on windows because it should be all the same user (running docker and owning the folders). tried to import after doing a fresh install and it works as it is.

I added a check for docker engine, if Docker Desktop (or the engine service really) is not running, the docker commands would fail.

**Comment by simjanos-dev** [comment]
Thank you!

Windows still warns that it is a malware. I guess there's not much that we can do about that, I'll add a disclaimer about it to the readme.

**Pull request merged**
