### PR TITLE
Isolate running containers from the dev environment

### PR DESCRIPTION
**Pull request by sergiolaverde0**
Currently, users must clone the repository and mount the code as a volume into the running containers since the current `Dockerfile` in `main` don't add the code to the images and instead are just a bundle of dependencies.

PR #2 already merged in `dev` has incorporated the code logic for the frontend inside the image, and this current PR does the same with the backend. It also modifies the `docker-compose.yml` to better represent how the folder for persistent data (what remains after the container goes down) can be any arbitrary position in the file tree.

This also means users can potentially not download and build images locally but instead download prebuilt images, such as those created by PR #50.

If ran as is its current limitations are:

- [x] Logs are not stored in the persistent storage which makes debugging potentially harder.
- [ ] Anything in `storage/framework` is not stored in the persistent storage. This is probably a minor issue, but it still is better kept documented.
- [x] Users can not trivially add dictionaries without using the commandline.

All of these are due to the default permissions on the folders created by docker when `your/linguacafe/folder` does not exist. While this can be solved by, for example, creating the folders beforehand and placing the dictionaries there before running the container, or running `sudo chmod 777 ./* -R` inside the folder in question like it is done currently, I am searching for a solution that is more friendly towards the user.

Any ideas?

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
Assuming logging is done using defaults, only a single file called `laravel.log` is necessary which does not clutter too much and can be put in the base directory instead of creating a `logs` subfolder.

Dictionaries can theoretically be handled the same way and it seems to work fine, but it could get a bit messy with too many of them so I am a little bit more reluctant to go down that route.

If done like that, the folder would look like this:
```
 .
├── jmdict_processed.txt
├── kanjidic2.xml
├── laravel.log
├── mysql
├── radical-strokes.txt
└── radicals.txt
```
Does not look too bad, as long as the user creates the folder before running `docker-compose up -d` no permissions must be changed (so no `sudo chmod 777` is needed), and once images get published to ghcr.io it is a single command for all steps, or two if you include creating the folder.

**Comment by simjanos-dev** [comment]
I'm not sure I understand correctly what it's supposed to do.

If the code is supposed to be pulled inside the docker image, where is the code that's on github will be added to the docker image, is there a missing git pull inside the  `docker/PhpDockerfile`  file? Or was this pull request created in a way that meant to be used together with #50 already?

I would prefer if logs had a separate folder, but we will definitely need one for dictionaries.

I am writing a UI for importing dictionaries now, so users won't have to manually run the import php scripts by opening urls. JMDict, CC-CEDICT and Wiktionary can be packaged together with LinguaCafe docker image if possible when we upload it to github, however there are some dictionaries that users must download themself manually because of Terms of Use, like dict.cc and put inside dictionaries folder. I don't know if it complicates things, but we will definitely need a dictionaries folder at least.

**Comment by sergiolaverde0** [comment]
> If the code is supposed to be pulled inside the docker image, where is the code that's on github will be added to the docker image, is there a missing git pull inside the `docker/PhpDockerfile` file? Or was this pull request created in a way that meant to be used together with #50 already?

Yes, that would be the way to go in the future since I'm using `COPY` to move the files into the image. For now what I did to test was clone the repo, build the images, then delete the repo to prove it isn't need to *run* the containers. After PR #50 is merged then the build is done once per version and the `docker-compose.yml` is changed to simply download them.

> I would prefer if logs had a separate folder, but we will definitely need one for dictionaries.
 
A nicer way to about this then would be pass the user the responsibility of creating those two folders before running `docker compose up -d`. I think this would be be reasonable enough to ask. This would be similar to how people using Jellyfin are asked to specify separate directories for cache, config and media in their compose files before running it.

> I am writing a UI for importing dictionaries now, so users won't have to manually run the import php scripts by opening urls. JMDict, CC-CEDICT and Wiktionary can be packaged together with LinguaCafe docker image if possible when we upload it to github, however there are some dictionaries that users must download themself manually because of Terms of Use, like dict.cc and put inside dictionaries folder. I don't know if it complicates things, but we will definitely need a dictionaries folder at least.

Those who can be put in this repo can just be put in `./storage/app/dictionaries/` and then they will be copied into the image and shipped with it. Adding the others should not have complications as long as the user creates the folder first.

**Comment by simjanos-dev** [comment]
I've learned about how github docker image publishing works, I will experiment with it and do it probably in a few days. 

Thank you so much for your help! @systemcrash too!

> Those who can be put in this repo can just be put in ./storage/app/dictionaries/ and then they will be copied into the image and shipped with it. Adding the others should not have complications as long as the user creates the folder first.

One file is almost 100MB,  I don't think I should be uploading it to the repo. That is why I put them on the Release page.

Also, wasn't there a problem that If you mount something over a copied directory, then the mounted directory overwrites the copied one (I can't find it now, maybe I remember it wrong)? If that's the case, then we would need 2 dictionaries directory. One for dictionaries which will be copied into the image and shipped, and one where the users can copy files to and it is mounted.

**Comment by sergiolaverde0** [comment]
Oh yeah you are right in both points, I derped because it was till fairly early here.

Yeah put them in releases or kink to their original sources (depending on licensing) and have users download and place them in the folder.

**Comment by simjanos-dev** [comment]
JMDict, CC CEDICT and Wiktionary allows it to be packaged together with the software (if I understood their license correctly). Is it possible to have them in the github image somehow, so it's more user friendly? It would save a step for the users. Maybe a download command in the dockerfile that downloads them from the github release download link?

**Comment by simjanos-dev** [comment]
Is the 3+GB image size (for the 3 images) any problem?

**Comment by sergiolaverde0** [comment]
> JMDict, CC CEDICT and Wiktionary allows it to be packaged together with the software (if I understood their license correctly). Is it possible to have them in the github image somehow, so it's more user friendly? It would save a step for the users. Maybe a download command in the dockerfile that downloads them from the github release download link?

Yes, it is possible. We can probably just `curl` or `wget` them at build time with a few lines in the `Dockerfile`.

> Is the 3+GB image size (for the 3 images) any problem?

Not *for now*. However, if you are going to ship more than a dozen of languages in Spacy and dictionaries for half of them it *might* get a little bit out of hand. These could be some famous last words, but I think leaving that aside for now and addressing it in the future is the best course of action because of how young this project still is.

**Comment by simjanos-dev** [comment]
Yeah, I was thinking about adding a config file that can enable/disable languages, but it has to be readable by the: dockerfile, python, javascript and php. So it's difficult. I'll stop adding new languages until that.

**Comment by systemcrash** [comment]
3gb?

Basically yes. The pull process takes time. The deps and amount of libs is
a lot. (It inspired me to see a rewrite in Go. Distant goals.)

As long as the image layers compress and the pull doesn't take more than a
few minutes, it's reasonable. But invoking languages could be done at
runtime and not compile time. Kicking the can down the road a bit but the
distro remains small and encourages anyone to try because it's small and
quick.

For those who want to "kick the tyres" and try it out, waiting 10-15
minutes to pull and unpack.... Well, you decide.

**Pull request merged**
