### PR TITLE
Partially working supervisord setup

### PR DESCRIPTION
**Pull request by sergiolaverde0**
With this, Horizon seems to be working correctly and websockets starts but fails to execute its function.

Logs also seem to have redundant information between themselves, which is not entirely an issue but might be work looking into to make debugging easier.

The change on the entrypoint allows to skip the step of running `composer install` manually, since I was missing that step and getting an error the first couple of tries.

Let me know if you have any question.

### CODE REVIEW

**Comment by sergiolaverde0** [comment]
And in case you are wondering: yes, the rest of the commands that we are currently running manually can also be added to the `entrypoint-dev.sh` just like I added the `supervisord` command, without impacting the users because the files are different.

**Comment by simjanos-dev** [comment]
Thank you so much! Ill take a look at this today or tomorrow. 

Maybe I made a mistake with websockets.

**Comment by sergiolaverde0** [comment]
Latest commit ensures all processes are managed by `supervisord` so that they are all treated equally and will all shut down gracefully when the container is asked to shut down. Before, I *think* the container was over once `apache2` was over, regardless of the state of the other two.
```
2024-07-09 23:04:57,814 INFO supervisord started with pid 1
2024-07-09 23:04:58,817 INFO spawned: 'apache2' with pid 58
2024-07-09 23:04:58,818 INFO spawned: 'horizon' with pid 59
2024-07-09 23:04:58,820 INFO spawned: 'websockets' with pid 60
2024-07-09 23:04:59,929 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-09 23:04:59,929 INFO success: horizon entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-09 23:04:59,929 INFO success: websockets entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

All that is left with this setup is to determine which messages should go to the container logs and which are better left on the logfiles. It is also possible to set a priority to the processes to they start and stop in a specific order, in case that is needed.

**Comment by simjanos-dev** [comment]
Thank you so much! it does work perfectly. ...which is a bit of bad news. Because if it was set up correctly at you, then it means the websockets service does not always work. I think I had 1 time when the service was running, but was not working.

Can you please provide more information about what goes wrong with the websockets? 

A few things:
- 6001 port has to be opened
- I said dictionary import progress is streamed real time, but it actually only sends updates after every 1000 records, so it is possible that if you imported a really small dictionary, you only saw 0% -> finished statuses.

An other place to confirm websockets work is importing a long text (any kind, can be a book). If you click the close button and open the book quickly, you can see chapters being processed and imported (there are a few tasks missing here).

**Comment by simjanos-dev** [comment]
I've merged this branch into dev. (Around 2 seconds before I realised that I should have waited until we figure out the websocket issue....)

**Comment by sergiolaverde0** [comment]
You can cherry pick those commits and move them to the other branch. Or undo the merge and ask me to open a new PR, whichever works for you.

I will test again tonight. Out of curiosity, in which order did the services start according to the logs? We might have a race condition here, which we already know how to solve.

**Comment by simjanos-dev** [comment]
```
2024-07-11 16:36:21,853 INFO spawned: 'apache2' with pid 61
2024-07-11 16:36:21,855 INFO spawned: 'horizon' with pid 62
2024-07-11 16:36:21,856 INFO spawned: 'websockets' with pid 63
2024-07-11 16:36:22,975 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-11 16:36:22,975 INFO success: horizon entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-11 16:36:22,975 INFO success: websockets entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

> You can cherry pick those commits and move them to the other branch. Or undo the merge and ask me to open a new PR, whichever works for you.

It's okay, probably won't cause any issues, we can keep it the way it is.

**Comment by sergiolaverde0** [comment]
> Can you please provide more information about what goes wrong with the websockets?

Tested again:

- No relevant information in the logs.
- When importing dictionaries I see no progress bar, it stays at 0% and then marks as completed. Tried with JMdict, Chinese Wiktionary, and Russian Wiktionary.
- When importing a large book, however, it does seem to work. With *Crimen y Castigo* in Spanish, I got it to show the first 22 chapters as normal, but then the 381 remaining had a not-quite-progress-bar and the header section of the book view was a spinner.
- Chapters didn't update while I was that on view though, I had to leave and go back to it for all chapters to be shown as ready.

**Comment by simjanos-dev** [comment]
It does not work. Ill try to test it more on the weekend.


Can you please check if your user has a uuid in the database?

**Comment by sergiolaverde0** [comment]
One thing I noticed was the warning that the third party websocket library in use was recently deprecated, and their repo recommends to use [Laravel Reverb](reverb.laravel.com) from the Laravel team directly.

I don't how much of a pain in the rear end would be to migrate something so recently written, and it was released a week ago so documentation might be flaky.

**Comment by simjanos-dev** [comment]
It uses the same protocol (pusher) as the current one, so it would be very easy to replace it, basically just configuration. However I will have to move to Laravel 11 before that, which I would have done anyways in the next few weeks. 

I'll replace it with laravel reverb before v0.14.

(I am still interested if the test in my previous message works for you)

**Comment by simjanos-dev** [comment]
Sorry, I was an idiot. There is a global.js file, where the host name is defined for websockets. I use lingua.cafe, so it did not work for you.

I moved to laravel11 and reverb. Laravel mostly works, and there's a configuration issue with reverb. I'll probably get them working on the weekend.

**Comment by sergiolaverde0** [comment]
That was a lot of work in a few hours. Let me know if you need me for more testing, for now it seems I got it right blind.

**Comment by simjanos-dev** [comment]
> That was a lot of work in a few hours

No, it was just easy to do. Literally just copy-pasted the old files to an empty Laravel11 project and installed different packages for websockets, because they work the same way. 

> Let me know if you need me for more testing

Thank you!

**Comment by simjanos-dev** [comment]
Laravel11 and reverb were merged into dev. Websockets client should use the url from your browser, so it should be working properly. I think I tested every feature, but if something is not working, I'll find it in the next few weeks. I also only tested on a fresh install.

I am going to finish the chapter importing section today, then finally I can move on to other tasks (stanza).

Thank you so much for setting up supervisor!

**Pull request merged**
