### PR TITLE
Final touches to migrate to ghcr.io

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This PR attempts to address the last details of the migration from locally built images to images pulled from ghcr.io, hence it assumes PR #50 has been merged.

This draft intents to address four main points:

- [ ] Update the install and update instructions.
- [ ] Add a migration guide for those running the older system.
- [ ] Specify the supported platforms.
- [ ] Fix the overly aggressive health check in the database container.

In case something else is missing for the next release, this is the place for it to be discussed and proposed.

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Just one thing, due to my incompetency. Can I click on edit in #50, and change the base branch to `dev`?

I've never done it, and got this message when I attempt it:

> Some commits from the old base branch may be removed from the timeline, and old review comments may become outdated.

I want to merge it in, but it has `main` as base branch.

**Comment by sergiolaverde0** [comment]
You will almost certainly have to resolve merge conflicts manually, but yes you can.

**Comment by simjanos-dev** [comment]
If I merge #50 , can i still use `docker compose build` to build it locally?

It looks a bit complicated for me. I definitely have to test it on dev first.

**Comment by sergiolaverde0** [comment]
I usually build them independently with `docker build . --file docker/PythonDockerfile --tag tag_for_python` and ` docker build . --file docker/PhpDockerfile --tag tag_for_php`. This might even be easier in your system since it does not try to do both at once by default.

**Comment by simjanos-dev** [comment]
I merged everything, including your code review comments to change things. I changed the branch from main to dev to test it. So the dev branch now should function like the final image publishing will, except it works on the dev branch until I test it.

I've got this error:
```
[build-and-push-docker-images](https://github.com/simjanos-dev/LinguaCafe/actions/runs/7521309542/job/20471982340#step:7:156)
buildx failed with: ERROR: failed to solve: failed to read dockerfile: open ./docker/PhPDockerfile: no such file or directory
```

I've also noticed that the `docker-compose.yml` file has this line:
`image: ghcr.io/simjanos-dev/linguacafe-python-service:dev`

But it's missing from the webserver service. Should I add 
`image: ghcr.io/simjanos-dev/linguacafe-webserver:dev`
to it?

**Comment by simjanos-dev** [comment]
I have found a typo. It seems to be working now, it's in progress.

**Comment by sergiolaverde0** [comment]
> But it's missing from the webserver service. Should I add
> `image: ghcr.io/simjanos-dev/linguacafe-webserver:dev`
> to it?

Yes, you should, I don't know how that escaped us.

I have also noticed the action ran successfully but I see no packages in the repo, and I don't know the cause. Your action is identical to mine except for [this line](https://github.com/simjanos-dev/LinguaCafe/blob/8f79f7a8ad6be7baeafbe8a4110f20cbd49a0a4b/.github/workflows/build-and-push.yml#L69C11-L69C11) which I left as is from the default. I don't know if that is the cause any more than you do.

**Comment by simjanos-dev** [comment]
It was successful, but when I tried to run docker compose up -d, I've got this message:

`Error response from daemon: Head "https://ghcr.io/v2/simjanos-dev/linguacafe-webserver/manifests/dev": unauthorized`

I've done the steps in the beginning of `build-and-push.yml` file, and created the github secret named `GHCR_LINGUA_PAT`. I'm not sure what's missing.

**Comment by sergiolaverde0** [comment]
> created the github secret named `GHCR_LINGUA_PAT`

Does that token have the right permissions to publish to ghcr.io? I am not sure but I presume is `write:package`.

**Comment by simjanos-dev** [comment]
Yes. I'm 99.9% sure, because I payed attention to it. 

@systemcrash any idea?

**Comment by simjanos-dev** [comment]
The instructions told me to:

```
 You just created a PAT
# visit linguacafe repo, Settings -> Secrets & Variables -> Actions -> Repo Secrets -> New
# Name: GHCR_LINGUA_PAT; Secret: <paste from clipboard>
```

I've named my secret `GHCR_LINGUA_PAT`, and not `GHCR_LINGUA_PAT;`. Is that `;` character intentional, should I include it in the name?

**Comment by simjanos-dev** [comment]
> I have also noticed the action ran successfully but I see no packages in the repo, and I don't know the cause. Your action is identical to mine except for this line which I left as is from the default. I don't know if that is the cause any more than you do.

I think I just realized what happened. I do have the packages in my repo. They are just private. I do not know how to modify the publish file, to make them public.

**Comment by simjanos-dev** [comment]
I got it. :) I could go to my settings manually, and change each package to public. How I won't have to do this with each release.

**Pull request merged**
