### PR TITLE
Slightly reduce image size

### PR DESCRIPTION
**Pull request by sergiolaverde0**
This changes to get the composer binary from its own docker image instead of running their installer and shrinks webserver image size by around 200MB.

I attempted to shrink it further by using `npm install --production` but that failed because some of the packages listed on `packages.json` as dev dependencies are actually needed from production, most notably mix.

Finally, it moves an environment variable from the `.env` file to the Dockerfile not to polute production environment.

I will now move on to try to install spacy models at runtime.

### CODE REVIEW

**Comment by simjanos-dev** [comment]
Huge thank you!

Not sure if that's what you meant, but I think Spacy models should be loaded from files if it works. If they are loaded from files, it is very easy to keep track of which models are available, which makes it easy to write UI for enabling and disabling them. Also if they are stored as files, they won't have to be reinstalled after each update. 

I plan to upload them as a release, just like dictionaries.

**Comment by simjanos-dev** [comment]
I will have to experiment with npm packages. There are a few packages in the devDependencies that I do not know if I need them or not. I will have to move them one by one and check if something stops working.

**Comment by sergiolaverde0** [comment]
> I think Spacy models should be loaded from files if it works

I don't think that's possible, looking at their [documentation](https://spacy.io/usage/models/) it seems like the files uploaded in their releases page are meant to be installed with pip be it remotely or locally, so that they can be imported from inside a Python program.

What I think we can do is create a new folder such as `storage/app/models` and then have them installed with `pip install --target=/var/www/html/storage/app/models https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl` at the press of a button on the admin panel and then add that location to `PYTHONPATH`.

If that sounds cursed, is because it is. I will nevertheless try it. I have also been thinking in splitting the Python image in language groups, but that would require them to do more manual work to select the image with the languages they want to use, and does nothing for the webservice (which I don't understand why is so darn big).

**Comment by simjanos-dev** [comment]
Based on the first answer on [this](https://stackoverflow.com/questions/69216523/spacy-download-en-core-web-lg-manually) page I think it's possible. If they would have installed it with pip, they wouldn't give a full path to the model I think. English is not my native language, but if I understand it well, the `Manual download and installation` section in the documentation you linked does not say that you have to have to install it with pip.

I will try it out, but it will take a week or two.

**Comment by sergiolaverde0** [comment]
You are right. I might be able to test it by simply adding the paths in `views.py` and downloading and extracting the files inside of `docker exec`. I will let you know how that goes.

**Comment by simjanos-dev** [comment]
I would recommend test it with a minimal python script, that seems easier.

**Comment by simjanos-dev** [comment]
If it works, then it is even more simple than I thought. I can just add an additional `if` statement on the python side. And I can force users to select a language on Laravel/Vue side that has a model downloaded, and they can download them manually. But I could also add a UI for it in a 3~ hours. 

This would also allow us to add a ton of missing Spacy models: Danish, Croatian, Lithuanian, Macedonian, Polish, Portuguese, Romanian, Slovenian, English. 

I want to do some other things first, but I could implement this in a few weeks.

(I also want to start learning some Japanese again. I've put it off for weeks after the release.)

**Comment by sergiolaverde0** [comment]
Speaking of Japanese, I did a very minimal change as a first test:

Changed it from `views.py` to load the local model and then removed it from the Dockerfile. The fact that removing a 11.5 MB model reduced the image size by more than 300 MB was a red flag already, and after placing the files in the right location and checking the logs on the container I saw this:
```
linguacafe-python-service  | ImportError: Japanese support requires SudachiPy and SudachiDict-core (https://github.com/WorksApplications/SudachiPy). Install with `pip install sudachipy sudachidict_core` or install spaCy with `pip install spacy[ja]`.
```
Installing those dependencies is possible, but would bloat the image back to its original size. I suspect this is the same for most other languages, where the model themselves are less than 15 MB for the sm variant but most drag dependencies with them. So I tried my cursed idea of using pip, and this one naturally installed dependencies:
```
pip install --target=/var/www/html/storage/app/model $(spacy info ja_core_news_sm --url)
```
After this the `model` folder was 373 MB big which is more in line with what you would expect, and after setting `PYTHONPATH` in the `docker-compose.yml` it worked just fine, and I was able to import Japanese dictionaries and ebooks, read them, set words as learned, check definitions (on the new sidebar I hadn't seen yet) and it all persisted after restarting the container. Running `pip install` to a mounted volume is the kind of thing you should not do, but it *technically* works.

Another idea I have been thinking about is having different images for different language groups and have the user pick one. People learning German and Japanese at the same will be damned so I don't like that solution either.

All of this said, I heartily agree with slowing down the development a bit.

**Comment by simjanos-dev** [comment]
Yeah, I've just just seen your commit on your branch and knew it didn't work. It seems like from the documentation page that you linked in the dependencies section that Japanese, Korean, Russian, Ukrainian and Chinese have dependencies, others don't.

Does not loading modules with dependencies affect RAM usage as well significantly? If so, it could still be beneficial to enable/disable languages.

I thought about multiple images as well, but I don't like it either. Maybe let people build manually who do not want to have all languages, and let them enable languages in .env file?

By the way, do you use LinguaCafe yourself? You helped an incredible amount, I hope you get something out of it as well.

**Comment by sergiolaverde0** [comment]
> Japanese, Korean, Russian, Ukrainian and Chinese have dependencies, others don't

We might gain a lot from a hybrid solution then. Bake all the other languages into the image, then have only these be installed on runtime.

> Does not loading modules with dependencies affect RAM usage as well significantly?

Never crossed my mind, normally I'd assume the system to be smarter than that but I will test it sometime this week.

> Maybe let people build manually who do not want to have all languages, and let them enable languages in .env file?

Sounds complex. I wonder if we can simply check if a language is present when starting the container and disabling it if it isn't. Then people building manually only have to delete what they don't want from the Dockerfile.

> By the way, do you use LinguaCafe yourself?

I actually don't, my English is good enough that I simply read and use a dictionary when I find a word I don't know yet, and my plans to learn German have been procrastinated for a long while already. And that's fine. This project gave the push I needed to start contributing to stop lurking and reading tutorials and start collaborating on a project that is useful to its users. Plus I am confident I will find an use for it soon.

**Pull request merged**
